import java.nio.file.Path

plugins {
    `java-library`
    idea
}

group = rootProject.group
version = rootProject.version
description = "Tools Sub Project"


configurations.all {
    exclude("org.apache.logging.log4j:*")
}

dependencies {

implementation(group = "com.fasterxml.jackson.core",     name = "jackson-core",                version = project.properties["jackson.version"] as String)
implementation(group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jdk8",       version = project.properties["jackson.version"] as String)
implementation(group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310",     version = project.properties["jackson.version"] as String)
implementation(group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-hibernate5", version = project.properties["jackson.version"] as String)



    annotationProcessor(libs.querdsl.apt) { artifact {classifier = "general"} }
    annotationProcessor(libs.javax.persistence.api)
    annotationProcessor(libs.javax.annotation.api)

    implementation(libs.javax.inject)

    // query dsl
    implementation(libs.querdsl.jpa)
    implementation(libs.querdsl.mongodb)
    implementation(libs.jetbrains.annotations)

    // The `javax.annotation-api` dependency is (re)declared here as `compileOnly`
    // to allow for annotations that are used in the code generated by QueryDSL.
    compileOnly(libs.javax.annotation.api)

    implementation(libs.bundles.logging.java)

}

// Exsiting way
dependencies {
    implementation(group = "com.fasterxml.jackson.core", name = "jackson-core", version = project.properties["jackson.version"] as String)
    implementation(group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jdk8", version = project.properties["jackson.version"] as String)
    implementation(group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version = project.properties["jackson.version"] as String)
    implementation(group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-hibernate5", version = project.properties["jackson.version"] as String)
}

// Version Catalog library
dependencies {
    implementation(libs.jackson.core)
    implementation(libs.jackson.datatype.jdk8)
    implementation(libs.jackson.datatype.jsr310)
    implementation(libs.jackson.datatype.hibernate5)
}

// Version Catalog bundles
dependencies {
    implementation(libs.bundles.jackson)
}



tasks.register("foo") {
    group = "Projects-Tools"
    doLast {
        println("tools foo task is triggered")
        println("utils project's name: " + projects.utils.name)
        println("utils project's group: " + projects.utils.group)
        println("utils project's version: " + projects.utils.version)
    }
}
